#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 18 15:50:14 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Latch_tb_behav -key {Behavioral:sim_1:Functional:Latch_tb} -tclbatch Latch_tb.tcl -view /home/it/Vivado_Projects/Lab4_Task1/Latch_tb_behav.wcfg -log simulate.log"
xsim Latch_tb_behav -key {Behavioral:sim_1:Functional:Latch_tb} -tclbatch Latch_tb.tcl -view /home/it/Vivado_Projects/Lab4_Task1/Latch_tb_behav.wcfg -log simulate.log

